### ISSUE TITLE
Instrumentation and Dashboard to support Planning KPIs

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-app#1182]
#### Measurement
- % of users who create an app
- % of users who share an app
- 7/30/90 day retention rates

#### Todo
- [x] Cross check that we have the data needed for these via new instrumentation
- [x] Add any missing event tracking
- [x] Setup a dashboard

**Comment by thisandagain** [comment]
Thanks @adamlofting ! :+1:

**Comment by adamlofting** [comment]
We're currently tracking clicks on share in the side menu, but I need to:
- [ ] investigate if we can see when a share is successfully completed, and if possible track that event instead

**Comment by thisandagain** [comment]
From IRC:
```
9:30 AM <thisandagain> adamlofting: looking at the socialsharing cordova plugin ... looks like we can add optional success / error callbacks that should help you with tracking
9:30 AM <thisandagain> adamlofting: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#4a-usage-on-ios-and-android
```

**Comment by adamlofting** [comment]
Retention rate metrics are just going to be based on GA data for now, but will become more meaningful once we have login (e.g. a desktop user can be retained if they continue to use the mobile app and vice versa). 

Additional instrumentation for social share is in this new PR: https://github.com/mozilla/webmaker-app/pull/1229

**Comment by adamlofting** [comment]
I've setup a simple Geckoboard dashboard as a starting point:

https://mozillafoundation.geckoboard.com/dashboards/0BFA0FC6AE74586F

@thisandagain doe this work for you?

**Comment by thisandagain** [comment]
Excellent! Thanks @adamlofting :+1:
